sudo: false
language: perl
perl:
    - "5.26"
    - "5.20"

install:
  - cpanm --no-skip-satisfied Search::Tools::UTF8 Text::CSV_XS Data::Dump DateTime::Format::Strptime || { cat ~/.cpanm/build.log ; false ; }
